import { env } from "../env";
import { FormConfig } from "../../types/formConfig";

export const FORM_901_CONFIG: FormConfig = {
  formId: "901",
  formName: "Demo 生產線 A",
  ragicPath: env.RAGIC_FORM_901_PATH,
  mainFields: {
    // NOTE: /forms API 的分頁結果目前回欄位「名稱」鍵，不是欄位 ID。
    startSchedule: "demo_start_schedule",
    workOrderNo: "demo_work_order_no",
    machineCode: "demo_machine_code",
    modificationStatus: "demo_modification_status",
    forgingMother: "demo_forging_mother",
    customerPartNo: "demo_customer_part_no",
    urgent: "demo_urgent",
    sortOrder: "demo_sort_order",
    size: "demo_size",
    plannedStartDate: "demo_planned_start_date",
    plannedEndDate: "demo_planned_end_date",
    estimatedHours: "demo_estimated_hours",
    prevPlanEndDate: "demo_prev_plan_end_date",
    targetQtyPc: "demo_target_qty_pc",
    pendingQty: "demo_pending_qty",
    producedQtyStat: "demo_produced_qty_stat",
    prevReportQtyPc: "demo_prev_report_qty_pc",
    prevReportQtyKg: "demo_prev_report_qty_kg",
    prevReportContainerQty: "demo_prev_report_container_qty",
    processName: "demo_process_name",
    defaultProcessCode: "demo_default_process_code",
    prodType: "demo_prod_type",
    workOrderType: "demo_work_order_type",
    currentMaterial: "demo_current_material",
    completedQty: "demo_completed_qty",
    processLossPc: "demo_process_loss_pc",
    finishedWireSize: "demo_finished_wire_size",
    status: "demo_status",
    ragicUnfinishedStatus: "demo_ragic_unfinished_status",
    sourceCloseStatus: "demo_source_close_status",
    workOrderRemark: "demo_work_order_remark",
    productUsageType: "demo_product_usage_type",
    moldCondition: "demo_mold_condition",
    createdBy: "demo_created_by",
    lastUpdatedAt: "demo_last_updated_at",
    primaryMaterial: "demo_primary_material",
    defaultMainMaterial: "demo_default_main_material",
    previousMachine: "demo_previous_machine",
    prevStationRunning: "demo_prev_station_running",
    prevStationStatus: "demo_prev_station_status",
    siteRunning: "demo_site_running",
    prevCompletePc: "demo_prev_complete_pc",
    prevCompleteKg: "demo_prev_complete_kg",
    prevCompleteContainer: "demo_prev_complete_container",
  },
  mainFieldFallbacks: {
    startSchedule: "9001102",
    workOrderNo: "9001040",
    machineCode: "9001045|demo_machine_code",
    modificationStatus: "9001082|demo_modification_status",
    forgingMother: "9001044",
    customerPartNo: "9001079",
    urgent: "9001088",
    sortOrder: "9001063",
    size: "9001085",
    plannedStartDate: "9001055|demo_planned_start_date",
    plannedEndDate: "9001057",
    estimatedHours: "9001087",
    prevPlanEndDate: "9001091",
    targetQtyPc: "9001060",
    pendingQty: "9001101",
    producedQtyStat: "9001075",
    prevReportQtyPc: "9001100",
    prevReportQtyKg: "9001099",
    prevReportContainerQty: "9001098",
    processName: "9001061|demo_process_name",
    defaultProcessCode: "9001043|demo_default_process_code",
    prodType: "9001201|demo_prod_type",
    workOrderType: "9001051",
    currentMaterial: "9001089",
    completedQty: "9001083",
    processLossPc: "9001076",
    finishedWireSize: "9001090",
    status: "9001049",
    sourceCloseStatus: "9001072",
    workOrderRemark: "9001056",
    productUsageType: "9001080",
    moldCondition: "9001081",
    createdBy: "9001064",
    lastUpdatedAt: "9001202",
    primaryMaterial: "9001084",
    defaultMainMaterial: "9001046",
    previousMachine: "9001112",
    prevStationRunning: "9001094",
    prevStationStatus: "9001095",
    siteRunning: "9001093",
    prevCompletePc: "9001092",
    prevCompleteKg: "9001097",
    prevCompleteContainer: "9001096",
  },
  subtableId: "_subtable_demo_reports",
  subtableFields: {
    date: "demo_date",
    plannedIdle: "demo_planned_idle",
    processCode: "demo_process_code",
    machineId: "demo_machine_id",
    operatorId: "demo_operator_id",
    operatorName: "demo_operator_name",
    inputOptions: "demo_input_options",
    shiftType: "demo_shift_type",
    startTime: "demo_start_time",
    endTime: "demo_end_time",
    breakTime: "demo_break_time",
    totalWorkTime: "demo_total_work_time",
    productionQty: "demo_production_qty",
    cumulativeQty: "demo_cumulative_qty",
    remark: "demo_remark",
    setupAdjustType: "demo_setup_adjust_type",
    setupAdjustMinutes: "demo_setup_adjust_minutes",
    countSetupTimeFlag: "demo_count_setup_time_flag",
    setupTimeStandardHours: "demo_setup_time_standard_hours",
    setupLossQtyPerPcs: "demo_setup_loss_qty_per_pcs",
    processLossQtyPerPcs: "demo_process_loss_qty_per_pcs",
    totalContainerQty: "demo_total_container_qty",
    containerUnit: "demo_container_unit",
    plannedIdleMinutes: "demo_planned_idle_minutes",
    unplannedIdleMinutes: "demo_unplanned_idle_minutes",
    absentOrTrainingMinutes: "demo_absent_or_training_minutes",
    noMaterialMinutes: "demo_no_material_minutes",
    waitingQcApprovalMinutes: "demo_waiting_qc_approval_minutes",
    meetingMinutes: "demo_meeting_minutes",
    cleaningMinutes: "demo_cleaning_minutes",
    rdSamplingMinutes: "demo_rd_sampling_minutes",
    supportOtherMachinesMinutes: "demo_support_other_machines_minutes",
    machineBreakdownMinutes: "demo_machine_breakdown_minutes",
    machineAdjustmentMinutes: "demo_machine_adjustment_minutes",
    othersMinutes: "demo_others_minutes",
    waitingForDiesMinutes: "demo_waiting_for_dies_minutes",
    testingDiesMinutes: "demo_testing_dies_minutes",
  },
  writeConfig: {
    subtableId: "_subtable_demo_reports",
    requiredFields: [
      "date",
      "processCode",
      "machineId",
      "operatorId",
      "startTime",
      "endTime",
      "productionQty",
    ],
    mainWriteFields: {
      startSchedule: "9001102",
      machineCode: "9001045",
      urgent: "9001088",
      sortOrder: "9001063",
      plannedEndDate: "9001057",
    },
    subtableWriteFields: {
      date: env.UPSTREAM_ACTIVITY_LOG_DATE_FIELD_ID,
      plannedIdle: "9001068",
      processCode: env.UPSTREAM_ACTIVITY_LOG_PROCESS_FIELD_ID,
      machineId: "9001032",
      operatorId: "9001035",
      operatorName: "9001036",
      inputOptions: "9001069",
      shiftType: "9001006",
      startTime: "9001004",
      endTime: "9001005",
      breakTime: "9001039",
      totalWorkTime: "9001034",
      productionQty: "9001007",
      remark: "9001077",
      setupAdjustType: "9001010",
      setupAdjustMinutes: "9001011",
      countSetupTimeFlag: "9001012",
      setupTimeStandardHours: "9001058",
      setupLossQtyPerPcs: "9001008",
      processLossQtyPerPcs: "9001009",
      totalContainerQty: "9001013",
      containerUnit: "9001014",
      plannedIdleMinutes: "9001015",
      unplannedIdleMinutes: "9001016",
      absentOrTrainingMinutes: "9001017",
      noMaterialMinutes: "9001019",
      waitingQcApprovalMinutes: "9001020",
      meetingMinutes: "9001021",
      cleaningMinutes: "9001022",
      rdSamplingMinutes: "9001018",
      supportOtherMachinesMinutes: "9001023",
      machineBreakdownMinutes: "9001025",
      machineAdjustmentMinutes: "9001026",
      othersMinutes: "9001028",
      waitingForDiesMinutes: "9001024",
      // Demo 保留完整停機分類，讓寫入與分析流程可被展示。
      testingDiesMinutes: "9001027",
    },
  },
  linkedFields: {
    machineId: {
      sourceFormPath: env.RAGIC_SOURCE_MACHINE,
      lookupFieldId: "demo_machine_code",
      displayFieldId: "demo_machine_name",
    },
    operatorId: {
      sourceFormPath: env.RAGIC_SOURCE_OPERATOR,
      lookupFieldId: "demo_operator_id",
      displayFieldId: "demo_operator_name",
    },
    processCode: {
      sourceFormPath: env.RAGIC_SOURCE_PROCESS,
      lookupFieldId: "demo_process_code",
      displayFieldId: "demo_process_name",
    },
  },
  displayFields: [
    "date",
    "machineId",
    "operatorName",
    "startTime",
    "endTime",
    "productionQty",
  ],
};
