import { env } from "../env";
import { FormConfig } from "../../types/formConfig";

export const FORM_105_CONFIG: FormConfig = {
  formId: "105",
  formName: "[105] Work Order Report — Process B",
  ragicPath: env.RAGIC_FORM_105_PATH,
  mainFields: {
    // NOTE: 105 列表檢視目前仍沿用 104 同構主欄位，但這裡改成明確配置，避免日後被 104 隱性牽動。
    startSchedule: "開始排程?",
    workOrderNo: "工令單單號",
    machineCode: "預設機台",
    modificationStatus: "修改狀態",
    forgingMother: "鍛造母件",
    customerPartNo: "客戶料號",
    urgent: "急件",
    sortOrder: "工作排序碼",
    size: "尺寸",
    plannedStartDate: "指定開始日期",
    plannedEndDate: "指定結束日期 [生產計畫]",
    estimatedHours: "預估所需工時",
    prevPlanEndDate: "[上製程]指定結束日期",
    targetQtyPc: "目標數pc",
    pendingQty: "待生產數量",
    producedQtyStat: "已生產數量統計(pc)",
    prevReportQtyPc: "[上一站]報工數量(pc)",
    prevReportQtyKg: "[上一站]報工重量(kg)",
    prevReportContainerQty: "[上一站]報工容器數",
    processName: "主製程簡稱",
    defaultProcessCode: "子製程類別代碼",
    prodType: "製程大分類代碼",
    workOrderType: "工令單種類",
    currentMaterial: "目前使用來料",
    completedQty: "完工量<br>(扣除製程耗損)",
    processLossPc: "製程損耗(pc)",
    finishedWireSize: "成品線徑",
    status: "工令狀態",
    ragicUnfinishedStatus: "更新[未結案]判斷",
    misCloseStatus: "結案狀態",
    workOrderRemark: "工令單備註",
    productUsageType: "產品料號用途種類",
    moldCondition: "模具況狀",
    createdBy: "建立者帳號",
    lastUpdatedAt: "最後修改日期",
    primaryMaterial: "指定主要來料",
    defaultMainMaterial: "[預設]主要製程來料",
    prevStationRunning: "上一站執行中",
    prevStationStatus: "上一站狀態",
    siteRunning: "本站執行中?",
    prevCompletePc: "[上一站]完工數pc",
    prevCompleteKg: "[上一站]完工重kg",
    prevCompleteContainer: "[上一站]完工容器數",
  },
  filterFields: {
    machineCode: "內製指定機台",
  },
  filterFieldFallbacks: {
    machineCode: "1006031",
  },
  mainFieldFallbacks: {
    startSchedule: "1032313",
    workOrderNo: "1005984",
    machineCode:
      "預設機台|預設內製機台|[標準]預設機台|[預設]機台對照碼|機台|1015511|機台排程表對照碼|1006031|1017833|[指定]機台對照碼",
    modificationStatus:
      "1028076|修改狀態|修改<br>狀態|修改&lt;br&gt;狀態|修改\n狀態",
    forgingMother: "1006030",
    customerPartNo: "1027829",
    urgent: "1028097",
    sortOrder: "1012079",
    size: "1028082",
    plannedStartDate:
      "1006860|指定開始日期|指定開始日期 [生產計畫]|指定開始日期[生產計畫]",
    plannedEndDate: "1007354",
    estimatedHours: "1028091",
    prevPlanEndDate: "1028488",
    targetQtyPc: "1010900",
    pendingQty: "1031920",
    producedQtyStat: "1017662",
    prevReportQtyPc: "1031763",
    prevReportQtyKg: "1031762",
    prevReportContainerQty: "1031760",
    processName: "1010917|主製程簡稱|摘要主製程簡稱",
    defaultProcessCode: "1005990|子製程類別代碼",
    prodType: "Prod.Type製程大分類代碼|製程大分類代碼",
    workOrderType: "1006401",
    currentMaterial: "1028248",
    completedQty: "1028077",
    processLossPc: "1017663",
    finishedWireSize: "1028249",
    status: "1006393",
    misCloseStatus: "1015378",
    workOrderRemark: "1007336",
    productUsageType: "1028014",
    moldCondition: "1028017",
    createdBy: "1012370",
    lastUpdatedAt: "109",
    primaryMaterial: "1028079",
    defaultMainMaterial: "1006250",
    prevStationRunning: "1031735",
    prevStationStatus: "1031736",
    siteRunning: "1031734",
    prevCompletePc: "1031545",
    prevCompleteKg: "1031759",
    prevCompleteContainer: "1031754",
  },
  // NOTE: 105 經 raw/read audit 後確認目前子表與 104 同構，但這裡保留獨立配置，未來欄位偏移時只改 105。
  subtableId: "_subtable_1002178",
  subtableFields: {
    date: "Date生產日期Production Date",
    plannedIdle: "Planned Idle計畫停機?",
    processCode: "PROCESS子製程別代碼",
    machineId: "Mach機台/Pack Type包裝類別",
    operatorId: "Operator ID操作者工號",
    operatorName: "Operator擔當姓名",
    inputOptions: "Input Options預設報工時間(選填)",
    shiftType: "Shift Type班別(正常Reg/加班OT)",
    startTime: "Start Time開工時間(H:M)",
    endTime: "End Time完工時間(H:M)",
    breakTime: "Break Time扣除休息時間(時Hr)",
    totalWorkTime: "Total Work Time總工時(時Hr)",
    productionQty: "Production Qty生產量/PCS",
    cumulativeQty: "依序累計量",
    remark: "Remark備註",
    setupAdjustType: "Setup/Adjust架車(BA)or調機(SA)",
    setupAdjustMinutes: "Setup/Adjust (Min)架.調車/分鐘",
    countSetupTimeFlag: "Count Setup Time計算架車時間? (v)",
    setupTimeStandardHours: "[標準]架車時間 (Hr)",
    setupLossQtyPerPcs: "Setup Loss架車損耗/PCS",
    processLossQtyPerPcs: "Process Loss製程損耗/PCS",
    totalContainerQty: "Total Container Qty結案容器數",
    containerUnit: "Container Unit結案容器單位",
    plannedIdleMinutes: "(P)Planned Idle計劃停機/分",
    unplannedIdleMinutes: "(S)Unplanned Idle自主停機/分",
    absentOrTrainingMinutes: "(M)Absent or Training人員請假.上課/分",
    noMaterialMinutes: "(C)待料No Material/分",
    waitingQcApprovalMinutes: "(E)Waiting for QC Approval 待判/分",
    meetingMinutes: "(Q)Meeting 開會/分",
    cleaningMinutes: "(N)Cleaning打掃/分",
    rdSamplingMinutes: "RD SamplingRD件試樣/分",
    supportOtherMachinesMinutes: "(H)Support Other Machines支援其他車台/分",
    machineBreakdownMinutes: "(D)Machine Breakdown 機台損壞/分",
    machineAdjustmentMinutes: "(K)Machine Adjustment 機台調機/分",
    othersMinutes: "(F)Others 其他/分",
    waitingForDiesMinutes: "(B)Waiting for Dies 待模/分",
    testingDiesMinutes: "(R)Testing Dies 試模/分",
  },
  writeConfig: {
    subtableId: "_subtable_1002178",
    requiredFields: [
      "date",
      "machineId",
      "operatorId",
      "startTime",
      "endTime",
      "productionQty",
    ],
    mainWriteFields: {
      machineCode: "1006031",
    },
    subtableWriteFields: {
      date: "1002190",
      plannedIdle: "1012814",
      processCode: "1002195",
      machineId: "1002192",
      operatorId: "1002219",
      operatorName: "1002220",
      inputOptions: "1012830",
      shiftType: "1002145",
      startTime: "1002142",
      endTime: "1002143",
      breakTime: "1005322",
      totalWorkTime: "1002218",
      productionQty: "1002146",
      remark: "1017751",
      setupAdjustType: "1002151",
      setupAdjustMinutes: "1002152",
      countSetupTimeFlag: "1002153",
      setupTimeStandardHours: "1009094",
      setupLossQtyPerPcs: "1002149",
      processLossQtyPerPcs: "1002150",
      totalContainerQty: "1002158",
      containerUnit: "1002159",
      plannedIdleMinutes: "1002160",
      unplannedIdleMinutes: "1002161",
      absentOrTrainingMinutes: "1002162",
      noMaterialMinutes: "1002164",
      waitingQcApprovalMinutes: "1002165",
      meetingMinutes: "1002166",
      cleaningMinutes: "1002167",
      rdSamplingMinutes: "1002163",
      supportOtherMachinesMinutes: "1002169",
      machineBreakdownMinutes: "1002171",
      machineAdjustmentMinutes: "1002172",
      othersMinutes: "1002174",
      waitingForDiesMinutes: "1002170",
      testingDiesMinutes: "1002173",
    },
  },
  linkedFields: {
    machineId: {
      sourceFormPath: env.RAGIC_SOURCE_MACHINE,
      lookupFieldId: "機台代碼",
      displayFieldId: "機台簡稱",
    },
    operatorId: {
      sourceFormPath: env.RAGIC_SOURCE_OPERATOR,
      lookupFieldId: "工號",
      displayFieldId: "姓名",
    },
    processCode: {
      sourceFormPath: env.RAGIC_SOURCE_PROCESS,
      lookupFieldId: "子製程別代碼Proc. Sub Category ID",
      displayFieldId: "製程別名稱Proc. Name",
    },
  },
  displayFields: [
    "date",
    "machineId",
    "operatorName",
    "startTime",
    "endTime",
    "productionQty",
  ],
};
